### PR TITLE
Integration specs

### PR DESCRIPTION
**Pull request by lucascomamala**
**n+1**
Make sure that the N+1 problem is solved when fetching all posts and their comments for a user

Log before:
241303352-62aee270-5408-4cb6-b7be-ea0cdce69c79

Log After:
Nothing to log :)

***

**Integration specs**
Use Capybara to write integration tests for each view in your project.

Think on the flow of things and group the tests of page in a way that makes sense. For example, one test would check for the things in the page and another test for clicking links on it.

**User index page:**

- I can see the username of all other users.
- I can see the profile picture for each user.
- I can see the number of posts each user has written.
- When I click on a user, I am redirected to that user's show page.

**user show page:**

- I can see the user's profile picture.
- I can see the user's username.
- I can see the number of posts the user has written.
- I can see the user's bio.
- I can see the user's first 3 posts.
- I can see a button that lets me view all of a user's posts.
- When I click a user's post, it redirects me to that post's show page.
- When I click to see all posts, it redirects me to the user's post's index page.

**User post index page:**

- I can see the user's profile picture.
- I can see the user's username.
- I can see the number of posts the user has written.
- I can see a post's title.
- I can see some of the post's body.
- I can see the first comments on a post.
- I can see how many comments a post has.
- I can see how many likes a post has.
- I can see a section for pagination if there are more posts than fit on the view.
- When I click on a post, it redirects me to that post's show page.

**Post show page:**

- I can see the post's title.
- I can see who wrote the post.
- I can see how many comments it has.
- I can see how many likes it has.
- I can see the post body.
- I can see the username of each commentor.
- I can see the comment each commentor left.

***

**Aditional specs added:**

All Pages
- Clicking on the logo takes you home
- Clicking on the page name takes you home
- Clicking on New Post take you to new post path

User Index page:
- Clicking on user image takes you to that user's show page

Post show page:
- Clicking on author's name takes you to that author's show page
- Clicking the like button increases the likes counter
- Clicking the like button twice leaves the likes counter the same
- Writing and submitting a comment increases the comment counter
- Writing and submitting a comment displays the comment

### CODE REVIEW

**Comment by addod19** [comment]
### Hi @lucascomamala, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the pair programming activity is done solo. We expect commit messages from both coding partners :man_technologist: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by vickymarz — CHANGES_REQUESTED** [review]
Hi @lucascomamala, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] Good job so far 👍🏽 I can see that some of your tests are failing. Kindly check it out.
IMG-20230526-WA0018

- Also i think the screenshot that you provided was not the expected screenshot. I think your screenshot should look like this
Screenshot_20230526-200204



_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lucascomamala** [comment]
I changed the screenshot, as for the failed tests I'm not getting that in my system:
Capture

In any case, those are the request specs, and this pull request is for the integration tests (the ones that live in spec/feature/)

**Review by Whoistolu — APPROVED** [review]
### Hi @lucascomamala and @Solobarine 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Screenshot 2023-05-26 at 20 26 11

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by vickymarz** [comment]
> I changed the screenshot, as for the failed tests I'm not getting that in my system: Capture
> 
> In any case, those are the request specs, and this pull request is for the integration tests (the ones that live in spec/feature/)

Sure, you are right. I didnt notice that. Sorry.

**Pull request merged**
